# Site settings
baseURL = "https://olivierbildstein.netlify.app"
languageCode = "en-us"
title = "Portfolio website for Olivier Bildstein"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-180675416-1"

# Enter your disqus shortname to enable comments
disqusShortname = "olivierbildstein"

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Olivier Bildstein"
  description = "Masters in Financial Analysis at London Business School"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found - sorry for that I'm new with R"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Oli"
    subtitle = "portfolio website"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Biography"
      url = "blogs/biography"

    [[params.navigation.links]]
      name = "Homework 1"
      url = "blogs/homework1/homework1"

    [[params.navigation.links]]
      name = "Homework 2"
      url = "blogs/homework2/homework2"

    [[params.navigation.links]]
      name = "Homework 3"
      url = "blogs/homework3/homework3"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Home"
      url = "blogs"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Welcome to the portfolio website of Olivier Bildstein"
    subtitle = "Masters in Financial Analysis student at London Business School"
    buttonText = "Discover more"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Biography"
      subtitle = "Education, work, hobbies and much more"
      image = "pic01.jpg"
      url = "blogs/biography"

    [[params.tiles.showcase]]
      title = "Academic research"
      subtitle = "Master's thesis on the valuation of Private Equity (in French)"
      image = "pic02.jpg"
      url = "blogs/T3 - Mémoire - Olivier Bildstein.pdf"

    [[params.tiles.showcase]]
      title = "Homework 1"
      subtitle = "Drinking habits, IMBD, Financial stocks returns, IBM HR"
      image = "pic03.jpg"
      url = "blogs/homework1/homework1"

    [[params.tiles.showcase]]
      title = "Homework 2"
      subtitle = "Climate change, GSS, Trump, Gapminder, Covid-19, Bike sharing"
      image = "pic04.jpg"
      url = "blogs/homework2/homework2"

    [[params.tiles.showcase]]
      title = "Homework 3"
      subtitle = "Youth risk behavior, IMBD, Omega Group, Yield curve, GDP"
      image = "pic05.jpg"
      url = "blogs/homework3/homework3"

    [[params.tiles.showcase]]
      title = "One more thing"
      subtitle = "Data Analytics applied to the Investment Fundamentals course"
      image = "pic06.jpg"
      url = "blogs/Final assignement - Group 28 - Report.pdf"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Professional aspirations"
    subtitle = """Now that you know a bit more about me, my preivous work experiences and my skills using the R language, allow me  to share with you my professional aspirations.
    I am looking for a full-time position starting in June 2021 in the field of alternative investments (Private Equity, Venture Capital, Private Debt, Secondaries, Co-investments, GP-stake, Fund of Funds...you name it)."""
    buttonText = "Interested? Contact me!"
    url = "contact"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "obildstein.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Mobile phone"
    phone = "+44 731 287 5815"

    [[params.contact.address]]
    title = "Address"
    street = "Located worldwide, like the art of graffiti..."

  # Footer section
  [params.footer]
    enable = true
    copyright = "Inspired by Kostis Christodoulou, made by Olivier Bildstein, sweat and tears"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/obildstein"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/obildstein"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/olivierbildstein"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/olivierbildstein"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/olivierbildstein/"
      label = "LinkedIn"